<?xml version="1.0" ?>
<robot name="omniveyor" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="steerAxisX" value="0.2074" />
  <xacro:property name="steerAxisY" value="0.2074" />
  <xacro:property name="pumpkinLength" value="0.2" />
  <xacro:property name="forkLength" value="0.02" />
  <xacro:property name="wheelRadius" value="0.05" />
  <xacro:property name="steerAxisZ" value="${wheelRadius+pumpkinLength/2}" />

  <!-- Powered Casters -->
  <xacro:property name="one_pcv_caster">
    <inertial>
      <mass value="7.92"/>
      <inertia ixx="0.0332" ixy="0" ixz="0"
          iyy="0.0332" iyz="0" izz="0.02532"/>
    </inertial>
    <collision name="collision_p">
      <geometry>
        <cylinder radius="0.025" length="${pumpkinLength}"/>
      </geometry>
    </collision>
    <collision name="collision_f">
      <origin xyz="${-forkLength/2} 0 ${-pumpkinLength/2}" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder radius="0.01" length="${forkLength}"/>
      </geometry>
    </collision>
    <visual name="visual_p">
      <geometry>
        <cylinder radius="0.025" length="${pumpkinLength}"/>
      </geometry>
    </visual>
    <visual name="visual_f">
      <origin xyz="${-forkLength/2} 0 ${-pumpkinLength/2}" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder radius="0.01" length="${forkLength}"/>
      </geometry>
    </visual>
  </xacro:property>

  <xacro:property name="one_pcv_wheel">
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.005" ixy="0" ixz="0"
          iyy="0.005" iyz="0" izz="0.01"/>
    </inertial>
    <collision>
      <geometry>
        <cylinder radius="${wheelRadius}" length="0.015"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <cylinder radius="${wheelRadius}" length="0.015"/>
      </geometry>
      <material name="flat_black"/>
    </visual>
  </xacro:property>

  <xacro:macro name="pcv_assembly" params="prefix">
    <!-- Caster -->
    <link name="${prefix}_poweredCaster">
      <xacro:insert_block name="one_pcv_caster"/>
    </link>
    <!-- Wheel -->
    <link name="${prefix}_wheel">
      <xacro:insert_block name="one_pcv_wheel"/>
    </link>
    <gazebo reference="${prefix}_wheel">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
      <slip1>0.0001</slip1>
      <slip2>0.0001</slip2>
      <material>Gazebo/FlatBlack</material>
    </gazebo>
    <!-- Steering joint -->
    <joint type="continuous" name="${prefix}_steer">
      <parent link="base_link"/>
      <child link="${prefix}_poweredCaster"/>
      <xacro:if value="${prefix == 'FL'}">
      <origin xyz="${steerAxisX} ${steerAxisY} ${steerAxisZ}" rpy="0 0 0"/>
      </xacro:if>
      <xacro:if value="${prefix == 'FR'}">
      <origin xyz="${steerAxisX} ${-steerAxisY} ${steerAxisZ}" rpy="0 0 0"/>
      </xacro:if>
      <xacro:if value="${prefix == 'RL'}">
      <origin xyz="${-steerAxisX} ${steerAxisY} ${steerAxisZ}" rpy="0 0 0"/>
      </xacro:if>
      <xacro:if value="${prefix == 'RR'}">
      <origin xyz="${-steerAxisX} ${-steerAxisY} ${steerAxisZ}" rpy="0 0 0"/>
      </xacro:if>
      <axis xyz="0 0 1"/>
    </joint>
    <!-- Rolling joint -->
    <joint type="continuous" name="${prefix}_wheel_axle">
      <parent link="${prefix}_poweredCaster"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${-forkLength} 0 ${-pumpkinLength/2}" rpy="0 ${pi/2} ${pi/2}"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- Powerd Caster steering joints -->
  <xacro:pcv_assembly prefix="FL"/>
  <xacro:pcv_assembly prefix="FR"/>
  <xacro:pcv_assembly prefix="RL"/>
  <xacro:pcv_assembly prefix="RR"/>
  
  <gazebo reference="base_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <gazebo reference="laser">
      <sensor name="laser" type="gpu_ray">
        <pose>0 0 0 0 -0 0</pose>
        <ray>
          <scan>
            <horizontal>
              <samples>720</samples>
              <resolution>1</resolution>
              <min_angle>-1.57</min_angle>
              <max_angle>1.57</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.05</min>
            <max>20</max>
            <resolution>0.01</resolution>
          </range>
        </ray>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.005</stddev>
        </noise>
        <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
          <topicName>scan</topicName>
          <frameName>laser</frameName>
        </plugin>
        <always_on>1</always_on>
        <update_rate>40</update_rate>
        <visualize>true</visualize>
      </sensor>
  </gazebo>

  <gazebo reference="cam_d1_link">
      <sensor name="imu_sensor" type="imu">
        <gravity>true</gravity>
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
          <topicName>/cam_d1/imu</topicName>
          <bodyName>cam_d1_link</bodyName>
          <updateRateHZ>0.0</updateRateHZ>
          <gaussianNoise>0.002</gaussianNoise>
          <xyzOffset>0 0 0</xyzOffset>
          <rpyOffset>0 0 0</rpyOffset>
          <frameName>cam_d1_link</frameName>
          <initialOrientationAsReference>false</initialOrientationAsReference>
        </plugin>
        <pose>0 0 0 0 0 0</pose>
      </sensor>
      <sensor name="camera" type="depth">
        <!--pose>0.001 -0.045 0.003 0 0 0</pose-->
        <pose> 0 0 0 0 0 0 </pose>
        <visualize>true</visualize>
        <update_rate>15</update_rate>
        <camera>
          <horizontal_fov>1.204</horizontal_fov>
          <image>
            <width>1280</width>
            <height>720</height>
            <format>R8G8B8</format>
          </image>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="camera_plugin" filename="libgazebo_ros_openni_kinect.so">
          <baseline>0.2</baseline>
          <alwaysOn>true</alwaysOn>
          <!-- Keep this zero, update_rate in the parent <sensor> tag
            will control the frame rate. -->
          <updateRate>0.0</updateRate>
          <cameraName>cam_d1</cameraName>
          <imageTopicName>/cam_d1/color/image_raw</imageTopicName>
          <cameraInfoTopicName>/cam_d1/color/camera_info</cameraInfoTopicName>
          <depthImageTopicName>/cam_d1/depth/image_rect_raw</depthImageTopicName>
          <depthImageCameraInfoTopicName>/cam_d1/depth/camera_info</depthImageCameraInfoTopicName>
          <pointCloudTopicName>/cam_d1/depth/color/points</pointCloudTopicName>
          <frameName>cam_d1_depth_link</frameName>
          <pointCloudCutoff>0.3</pointCloudCutoff>
          <pointCloudCutoffMax>8.0</pointCloudCutoffMax>
          <distortionK1>0</distortionK1>
          <distortionK2>0</distortionK2>
          <distortionK3>0</distortionK3>
          <distortionT1>0</distortionT1>
          <distortionT2>0</distortionT2>
          <CxPrime>0</CxPrime>
          <Cx>0</Cx>
          <Cy>0</Cy>
          <focalLength>0</focalLength>
          <hackBaseline>0</hackBaseline>
        </plugin>
      </sensor>
  </gazebo>

  <gazebo reference="cam_d2_link">
      <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <gravity>true</gravity>
        <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
          <topicName>/cam_d2/imu</topicName>
          <bodyName>cam_d2_link</bodyName>
          <updateRateHZ>0.0</updateRateHZ>
          <gaussianNoise>0.002</gaussianNoise>
          <xyzOffset>0 0 0</xyzOffset>
          <rpyOffset>0 0 0</rpyOffset>
          <frameName>cam_d2_link</frameName>
          <initialOrientationAsReference>false</initialOrientationAsReference>
        </plugin>
        <pose>0 0 0 0 0 0</pose>
      </sensor>
      <sensor name="camera" type="depth">
        <!--pose>0.001 -0.045 0.003 0 0 0</pose-->
        <pose> 0 0 0 0 0 0 </pose>
        <visualize>true</visualize>
        <update_rate>15</update_rate>
        <camera>
          <horizontal_fov>1.204</horizontal_fov>
          <image>
            <width>1280</width>
            <height>720</height>
            <format>R8G8B8</format>
          </image>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="camera_plugin" filename="libgazebo_ros_openni_kinect.so">
          <baseline>0.2</baseline>
          <alwaysOn>true</alwaysOn>
          <!-- Keep this zero, update_rate in the parent <sensor> tag
            will control the frame rate. -->
          <updateRate>0.0</updateRate>
          <cameraName>cam_d2</cameraName>
          <imageTopicName>/cam_d2/color/image_raw</imageTopicName>
          <cameraInfoTopicName>/cam_d2/color/camera_info</cameraInfoTopicName>
          <depthImageTopicName>/cam_d2/depth/image_rect_raw</depthImageTopicName>
          <depthImageCameraInfoTopicName>/cam_d2/depth/camera_info</depthImageCameraInfoTopicName>
          <pointCloudTopicName>/cam_d2/depth/color/points</pointCloudTopicName>
          <frameName>cam_d2_depth_link</frameName>
          <pointCloudCutoff>0.3</pointCloudCutoff>
          <pointCloudCutoffMax>6.0</pointCloudCutoffMax>
          <distortionK1>0</distortionK1>
          <distortionK2>0</distortionK2>
          <distortionK3>0</distortionK3>
          <distortionT1>0</distortionT1>
          <distortionT2>0</distortionT2>
          <CxPrime>0</CxPrime>
          <Cx>0</Cx>
          <Cy>0</Cy>
          <focalLength>0</focalLength>
          <hackBaseline>0</hackBaseline>
        </plugin>
      </sensor>
  </gazebo>

  <gazebo>
    <plugin filename="libOmniVeyorPlugin_ROS.so" name="omniveyor_simulator"/>
  </gazebo>
</robot>
